#!/bin/zsh

# Fetch a file or directory, backup and delete existing copies and create directories.
# A SRC with a trailing slash is treated as a directory (fetched/linked/cleared recursively)
# rather than a single file.
setup() {
	TYPE=$1
	SRC=$2
	DST=$3

	# If no destination is set, place in the home directory
	if [[ -z $3 ]]; then
		DST="$HOME/$(basename $SRC)"
	fi

	# A trailing slash on SRC marks it as a directory
	IS_DIR=0
	if [[ $SRC == */ ]]; then
		IS_DIR=1
		SRC=${SRC%/}
		DST=${DST%/}
	fi

	# Back up (copy) existing destination files/directories
	if [[ -e $DST || -L $DST ]]; then
		echo "Backing up existing $([[ $IS_DIR -eq 1 ]] && echo directory || echo file) \"$(basename $DST)\"."
		cp -r $DST "$DST.bak"
		rm -rf $DST
	fi

	# Create nested directories if they do not exist
	mkdir -p $(dirname $DST)

	if [[ $TYPE == "fetch" ]]; then
		if [[ $IS_DIR -eq 1 ]]; then
			# Fetch a whole directory by pulling down the repo tarball and
			# copying out just the subdirectory we want
			echo "Fetching directory \"$(basename $SRC)\" to \"$DST\"."
			mkdir -p $DST
			TMPDIR_FETCH=$(mktemp -d)
			curl -sL https://codeload.github.com/MatthewWid/dotfiles/tar.gz/refs/heads/master -o "$TMPDIR_FETCH/repo.tar.gz"
			tar -xzf "$TMPDIR_FETCH/repo.tar.gz" -C "$TMPDIR_FETCH"
			cp -r "$TMPDIR_FETCH"/dotfiles-master/dotfiles/$SRC/. "$DST/"
			rm -rf "$TMPDIR_FETCH"
		else
			# Fetch a single file from remote website
			echo "Fetching \"$(basename $SRC)\" to \"$DST\"."
			curl -sL https://raw.githubusercontent.com/MatthewWid/dotfiles/refs/heads/master/dotfiles/$SRC -o $DST
		fi
	elif [[ $TYPE == "link" ]]; then
		# Link the file or directory from current directory to destination
		echo "Syncing \"$(basename $SRC)\" to \"$DST\"."
		ln -sf "$(realpath -m $SRC)" "$(realpath -m $DST)"
	elif [[ $TYPE == "clear" ]]; then
		echo "Clearing \"$(basename $SRC)\" from \"$DST\"."
		# Clear existing files/directories
		# To delete backup files, too, add: `rm -rf "$DST.bak"` here and re-run
		rm -rf $DST
	fi
}

# Download/Symlink all configuration files to their appropriate locations
# If using the `sync` option, should be run from within the Dropbox `dotfiles` directory
run() {
	if [[ $1 != "fetch" && $1 != "link" && $1 != "clear" ]]; then
		echo "Improper sync type given: \"$1\"."
		exit 1
	fi

	setup $1 .tmux.conf & \
	setup $1 .gitignore-global & \
	setup $1 .gitconfig & \
	setup $1 .fdignore & \
	setup $1 .inputrc & \
	setup $1 .gdbinit & \
	setup $1 nvim/ ~/.config/nvim/ & \
	setup $1 .zshrc & \
	setup $1 aliases.zsh $ZSH_CUSTOM/aliases.zsh & \
	setup $1 bin/devenv ~/bin/devenv & \
	setup $1 ranger/commands.py ~/.config/ranger/commands.py & \
	setup $1 ranger/commands_full.py ~/.config/ranger/commands_full.py & \
	setup $1 ranger/rc.conf ~/.config/ranger/rc.conf & \
	setup $1 ranger/rifle.conf ~/.config/ranger/rifle.conf & \
	setup $1 ranger/scope.sh ~/.config/ranger/scope.sh & \
	setup $1 bat/config ~/.config/bat/config & \
	wait
}

run $1
